# Generated by Django 4.2.7 on 2023-11-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('record_time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_date', to='core.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_date', to='core.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Visit_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visit_desc', models.TextField()),
                ('hospitalization', models.BooleanField()),
                ('medical_records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_forms', to='visit.medical_record')),
                ('visit_dates_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_forms', to='visit.visit_date')),
            ],
        ),
    ]
