# Generated by Django 4.2.7 on 2023-11-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient_share', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('the_remaining_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('insurance_contribution', models.DecimalField(decimal_places=2, max_digits=20)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='core.patients')),
            ],
        ),
    ]
